# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: position_controllers/GripperActionController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position

gripper_controller:
  ros__parameters:
    joint: meca_gripper_finger1_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.001
    max_effort: 10.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0